### ISSUE TITLE
 Sprint objective: To get (meta)data from EBI ingest to the TDR staging bucket as quickly and simply as possible.

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#141]
User story: As a data contributor I want to submit my project to the DCP2 so that it is available to the scientific community.

- [ ] KR1: Ensure all projects which we have archived or curated since DCP1 maintenance mode are in a suitable state to be exported to DCP2 and assess which will be the simplest to use as a test case.

- [x] KR 2: By mid way through the sprint have a prototype which has been tested with the simplest real example.

- [x] KR3: By the end of the sprint we have completed two learn - build - measure cycles.

- [x] KR4: By the end of the sprint we have non-DCP1 data and metadata submission in the terra staging area.

**Comment by clairerye** [comment]
Closing as completed sprint goal
