### ISSUE TITLE
Add to and update the Meyer dataset in public archives with DSP

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-dev-team#27]
**Description of the task:**

As the primary data wrangler for the Kerstin Meyer Tissue Sensitivity dataset #86 I need to  ensure that existing submissions are updated with new uuids and add the new samples and files to BioSamples and ENA

Project in the HCA browser:
https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7

**Acceptance criteria for the task:**

- [ ] Existing entities in BioSamples updated with new uuids and any attribute/modelling mapping changes
- [ ] New biomaterials and associated metadata added to BioSamples
- [ ] Existing project in BioStudies updated with new uuid, any attribute/modelling mapping changes and updated abstract from data.humancellatlas.org submission
- [ ] Existing submissions in ENA updated with new uuids
- [ ] New files submitted to ENA 

Dependent on current work being done to improve the existing archiving script
#6 
#21 

Let me know if you require any further information about this task

**Comment by justincc** [comment]
We have no mechanism for doing archive updates at this point and it may take a long time to construct one. Prioritizing this task will require a conversation with @lauraclarke as product owner.

**Comment by lauraclarke** [comment]
Why is archive updates more complex than DSS updates?

**Comment by mshadbolt** [comment]
If it will be too hard for ingest-devs I can take back and figure out how to do it manually, will let @lauraclarke decide which is best.

**Comment by lauraclarke** [comment]
@justincc based on a quick chat with Melanie, that I would be happy to confirm with Karoly and Haseeb, making updates is no more complex than making new submissions, the most significant difference is you have to embed the archive accession of the thing you are updating in the submission. 

I understand the plan to get new submissions working first but this feels like it shouldn't be a significantly more complex operation and should be doable without much extra work once new submissions are working.

Do you have information to suggest updates are more complex and require a lot more heavy lifting than new submissions? Thankfully DSP is a much simpler system to the DSS.

There is an urgency to the Meyer submission so I understand @mshadbolt desire to get this done rapidly

**Comment by justincc** [comment]
There is unknown additional complexity for the scripts ingest would use to do updates. We will need to quantify this first. We will do that after we have the basic system working again.

**Comment by mshadbolt** [comment]
This paper is now published which refers to the BioProject which is not up to date so I see this as high priority https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1906-x#availability-of-data-and-materials

**Comment by lauraclarke** [comment]
As the ingest service does not have functional new submissions I think to do this will require extending Enrique's tool to make sure it can use the subs-2 team and that is can make updates.

**Comment by mshadbolt** [comment]
ok I will work with @ESapenaVentura to look at updating this and consult ingest team as needed if we get stuck

**Comment by clairerye** [comment]
@mshadbolt and @justincc can I check that this is now essentially resolved as the Meyer dataset has now made it through DSP and into the archives? So I can close the ticket?

**Comment by mshadbolt** [comment]
yep will close
