### ISSUE TITLE
Update all prod data with reference to non prod schema urls 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#384]

**Comment by aaclan-ebi** [comment]
This ticket has a prerequisite once updates implementation is promoted to prod. ebi-ait/dcp-ingest-central#77
I believe the describedBy can be simply updated via Ingest API, the metadata should be revalidated and reexported.

Identified projects/submissions:

* using dev schema urls:
project short name: "Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation."
https://contribute.data.humancellatlas.org/projects/detail/5cdb0348d96dad000858fff6

* using staging schema urls

EmbryonicHindlimb - https://contribute.data.humancellatlas.org/projects/detail/5f0446623d2910077dd42dcb - Exported (dcp2 data)


The following can be reingested:
MouseLungMyofibroblasts - https://contribute.data.humancellatlas.org/projects/detail/5ebaad94e952846aff4f0351 - Draft 
TestisCellAtlas - https://contribute.data.humancellatlas.org/projects/detail/5fac15fa706b4c65fc988c08 - Valid
HnsccImmuneLandscape - https://contribute.data.humancellatlas.org/projects/detail/5fb3a3f4706b4c65fc989c17 - Valid

**Comment by jacobwindsor** [comment]
- https://contribute.data.humancellatlas.org/projects/detail/5cdb0348d96dad000858fff6
  - Updated to prod URL using 14.0.0 version
- https://contribute.data.humancellatlas.org/projects/detail/5f0446623d2910077dd42dcb
  - Updated to prod URL using 14.1.0 version
- https://contribute.data.humancellatlas.org/projects/detail/5ebaad94e952846aff4f0351
  - Updated to prod URL using 14.1.0
- https://contribute.data.humancellatlas.org/projects/detail/5fac15fa706b4c65fc988c08
  - Unable to update due to StackOverflow error (will investigate)
- https://contribute.data.humancellatlas.org/projects/detail/5fb3a3f4706b4c65fc989c17
  - Already using prod URL

**Comment by jacobwindsor** [comment]
This is blocked by work on [bulk updates](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/147)

**Comment by aaclan-ebi** [comment]
I re-exported the submission for this project https://contribute.data.humancellatlas.org/projects/detail/5f0446623d2910077dd42dcb
so that Wei can create a new submission for new data.

@Wkt8 will submit the form for Data Import

**Comment by Wkt8** [comment]
Have submitted the form for Data Import

**Comment by jacobwindsor** [comment]
Some explanation as to why this is blocked by bulk updates. [This project](https://contribute.data.humancellatlas.org/projects/detail/5cdb0348d96dad000858fff6) contains ~5000 metadata entities, each of which will need updating. I had written a script to update each one by one with prod schema URLs but it was going to take a while and we decided to stop at some point and wait for bulk updates.

**Comment by Wkt8** [comment]
Halted and blocked by migration work.

**Comment by ofanobilbao** [comment]
I believe this is no longer blocked right?

**Comment by ofanobilbao** [comment]
This seemed to be lead by Alegria and Jacob. Probably worth Alexie assessing it to evaluate what remains to be done and how much work that would entail.

**Comment by idazucchi** [comment]
- https://contribute.data.humancellatlas.org/projects/detail/5cdb0348d96dad000858fff6
  - [x] Exported
  - [x] on the portal  
- https://contribute.data.humancellatlas.org/projects/detail/5f0446623d2910077dd42dcb
  - [x] Exported 
  - [ ] Portal - waiting for R42 to go live - see [dataset ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/1265)
- https://contribute.data.humancellatlas.org/projects/detail/5ebaad94e952846aff4f0351
  - [x]  Updated to prod URLs
  - [x] Critical 10x metadata is missing - see [ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/86) - blocked indefinitely 
- https://contribute.data.humancellatlas.org/projects/detail/5fac15fa706b4c65fc988c08
  - [ ] Blocked by gender schema update - see [dataset ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/167)
- https://contribute.data.humancellatlas.org/projects/detail/5fb3a3f4706b4c65fc989c17
  - [x] Updated to prod URLs (this one was already using prod URLs)
  - [x] Valid
  - [x] Exported
  - [x] on the portal

The datasets that are still open have dedicated tickets on the wrangling board - we can close this ticket
